version: '2.1'
services:
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=testusr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    restart: always
    image: app
    build: .
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    depends_on:
      - database
    entrypoint: ["python", "manage.py","runserver"]
  